import type { TestCase } from "../models/test-case.js";

/**
 * Accessibility-tree probe generation (optimization plan Phase 4, "Live
 * Reconcile").
 *
 * The source plan proposed `xcrun simctl ui <udid> dump` for this. That
 * subcommand does not exist — `simctl ui` only supports `appearance`,
 * `increase_contrast` and `content_size`, and simctl exposes no accessibility
 * dump at all. The workable equivalent is a tiny XCUITest class that walks
 * `XCUIApplication().descendants(matching: .any)` and attaches the tree as JSON,
 * which XForge then extracts from the result bundle with `xcresulttool`.
 *
 * Because the probe needs the app installed, it runs *after* the single
 * build-for-testing and *before* the shard matrix — it does not save the build,
 * it saves running the whole matrix into timeouts when the UI has drifted.
 */

/** Screens the probe should visit, derived from the plan's locators. */
export function probeTargets(cases: TestCase[]): string[] {
  const targets = new Set<string>();
  for (const testCase of cases) {
    for (const step of testCase.steps) {
      if (step.action === "open" && step.target) targets.add(step.target);
    }
    for (const assertion of testCase.assertions) {
      if (assertion.kind === "screen-is" && assertion.target) {
        targets.add(assertion.target);
      }
    }
  }
  return [...targets].sort();
}

function swiftString(value: string): string {
  return JSON.stringify(value);
}

/**
 * Generate `XForgeProbeTests.swift`. One test method dumps the tree for every
 * target screen; failures to reach a screen are recorded in the dump rather
 * than thrown, so a single unreachable screen never hides the rest.
 */
export function generateProbeFile(cases: TestCase[]): string {
  const targets = probeTargets(cases);
  const lines: string[] = [
    "// Generated by XForge Test — do not edit by hand.",
    "// Accessibility probe: dumps the real element tree so XForge can compare",
    "// it with the Canonical Project Model before running the full matrix.",
    "import XCTest",
    "",
    "final class XForgeProbeTests: XCTestCase {",
    "    private struct ProbeElement: Encodable {",
    "        let identifier: String",
    "        let label: String",
    "        let type: String",
    "        let isEnabled: Bool",
    "        let isHittable: Bool",
    "        let width: Double",
    "        let height: Double",
    "    }",
    "",
    "    private struct ProbeScreen: Encodable {",
    "        let target: String",
    "        let reached: Bool",
    "        let elements: [ProbeElement]",
    "    }",
    "",
    "    func test_XForgeProbe() throws {",
    "        let app = XCUIApplication()",
    '        app.launchArguments = ["--xforge-test", "--xforge-probe"]',
    "        app.launch()",
    "",
    `        let targets = [${targets.map(swiftString).join(", ")}]`,
    "        var screens: [ProbeScreen] = []",
    '        screens.append(dump(app, target: "__root__", reached: true))',
    "",
    "        for target in targets {",
    "            let entry = app.descendants(matching: .any)[target].firstMatch",
    "            let reached = entry.waitForExistence(timeout: 5)",
    "            if reached && entry.isHittable { entry.tap() }",
    "            screens.append(dump(app, target: target, reached: reached))",
    "        }",
    "",
    "        let data = try JSONEncoder().encode(screens)",
    '        let attachment = XCTAttachment(data: data, uniformTypeIdentifier: "public.json")',
    '        attachment.name = "xforge-probe"',
    "        attachment.lifetime = .keepAlways",
    "        add(attachment)",
    "    }",
    "",
    "    private func dump(",
    "        _ app: XCUIApplication,",
    "        target: String,",
    "        reached: Bool",
    "    ) -> ProbeScreen {",
    "        let all = app.descendants(matching: .any).allElementsBoundByIndex",
    "        let elements = all.prefix(500).map { element in",
    "            ProbeElement(",
    "                identifier: element.identifier,",
    "                label: element.label,",
    "                type: String(describing: element.elementType),",
    "                isEnabled: element.isEnabled,",
    "                isHittable: element.isHittable,",
    "                width: Double(element.frame.width),",
    "                height: Double(element.frame.height)",
    "            )",
    "        }",
    "        return ProbeScreen(target: target, reached: reached, elements: Array(elements))",
    "    }",
    "}",
    "",
  ];
  return lines.join("\n");
}

/** One element as dumped by the generated probe. */
export interface ProbeElement {
  identifier: string;
  label: string;
  type: string;
  isEnabled: boolean;
  isHittable: boolean;
  width: number;
  height: number;
}

export interface ProbeScreen {
  target: string;
  reached: boolean;
  elements: ProbeElement[];
}

/**
 * Turn a probe dump into the identifier inventory the reconciler consumes, so
 * the *same* comparison runs against static source and against live UI.
 */
export function inventoryFromProbe(
  screens: ProbeScreen[],
  feature?: string,
): Array<{
  value: string;
  expression: string;
  file: string;
  dynamic: boolean;
  feature?: string;
}> {
  const seen = new Set<string>();
  const inventory: Array<{
    value: string;
    expression: string;
    file: string;
    dynamic: boolean;
    feature?: string;
  }> = [];
  for (const screen of screens) {
    for (const element of screen.elements) {
      const id = element.identifier.trim();
      if (id.length === 0 || seen.has(id)) continue;
      seen.add(id);
      inventory.push({
        value: id,
        expression: id,
        file: `probe:${screen.target}`,
        dynamic: false,
        ...(feature ? { feature } : {}),
      });
    }
  }
  return inventory;
}

/** Screens the probe could not reach — a navigation deviation, not a bug. */
export function unreachableScreens(screens: ProbeScreen[]): string[] {
  return screens
    .filter((s) => !s.reached && s.target !== "__root__")
    .map((s) => s.target);
}
