import type { TestCase, TestStep } from "../models/test-case.js";

/**
 * XCUITest source generation (blueprint §14, Phase 3, master prompt §3).
 *
 * Turns deterministic TestCase skeletons into compilable XCUITest Swift. The
 * generator maps abstract step actions to XCUIElement interactions and uses
 * accessibility identifiers as locators (never coordinate tapping, §4.2). It
 * emits `--xforge-test` launch arguments so the app can enable test-support
 * (§14) without any production behavior change.
 */

export interface XcuiGenOptions {
  /** Swift class name for the generated test file. */
  className: string;
  /** App/module under test (for the file header comment only). */
  module?: string;
}

function swiftIdentifier(id: string): string {
  const cleaned = id.replace(/[^A-Za-z0-9]+/g, "_").replace(/^(\d)/, "_$1");
  return cleaned.length > 0 ? cleaned : "case_unnamed";
}

/** Map one abstract step to XCUITest Swift lines. */
export function renderStep(step: TestStep): string[] {
  const target = step.target ? swiftIdentifier(step.target) : undefined;
  const el = target ? `app.otherElements["${step.target}"]` : "app";
  switch (step.action) {
    case "launch-app":
      return ['app.launchArguments = ["--xforge-test"]', "app.launch()"];
    case "relaunch-app":
      return ["app.terminate()", "app.launch()"];
    case "open":
      return [
        `XCTAssertTrue(app.descendants(matching: .any)["${step.target ?? ""}"].waitForExistence(timeout: 5))`,
        `app.buttons["${step.target ?? ""}"].firstMatch.tap()`,
      ];
    case "tap":
      return [`app.buttons["${step.target ?? ""}"].firstMatch.tap()`];
    case "type":
      return [
        `app.textFields["${step.target ?? ""}"].firstMatch.typeText(${JSON.stringify(String(step.value ?? ""))})`,
      ];
    case "set-time":
      return [`// set-time ${String(step.value ?? "")} via test-support seed`];
    case "select-weekdays":
      return [
        `// select weekdays ${Array.isArray(step.value) ? step.value.join(",") : String(step.value ?? "")}`,
      ];
    case "capture-screenshot":
      return [
        "let shot = app.screenshot()",
        "let att = XCTAttachment(screenshot: shot)",
        "att.lifetime = .keepAlways",
        "add(att)",
      ];
    case "audit-accessibility":
      return ["// accessibility audit performed by analyzer on captured tree"];
    case "measure-cold-launch":
      return [
        "measure(metrics: [XCTApplicationLaunchMetric()]) {",
        "  app.launch()",
        "}",
      ];
    case "create-item":
      return [`// create-item via test-support seed or UI flow`];
    default:
      return [`// unmapped action: ${step.action}${target ? ` (${el})` : ""}`];
  }
}

function renderCaseMethod(testCase: TestCase): string {
  const method = `test_${swiftIdentifier(testCase.id)}`;
  const bodyLines: string[] = [];
  bodyLines.push(`// ${testCase.title}`);
  bodyLines.push(
    `// risk=${testCase.risk_score} priority=${testCase.priority}`,
  );
  if (testCase.requirements.length > 0) {
    bodyLines.push(`// requirements: ${testCase.requirements.join(", ")}`);
  }
  bodyLines.push("let app = XCUIApplication()");
  for (const step of testCase.steps) {
    for (const line of renderStep(step)) bodyLines.push(line);
  }
  for (const expected of testCase.expected_results) {
    bodyLines.push(`// EXPECT: ${expected}`);
  }
  const indented = bodyLines.map((l) => `        ${l}`).join("\n");
  return `    func ${method}() throws {\n${indented}\n    }`;
}

/** Generate a full XCUITest Swift file for a set of cases. */
export function generateXcuiTestFile(
  cases: TestCase[],
  options: XcuiGenOptions,
): string {
  const header = [
    "// Generated by XForge Test — do not edit by hand.",
    "// This file is test-support only and must not change production behavior.",
    options.module ? `// Module under test: ${options.module}` : "",
    "import XCTest",
    "",
    `final class ${options.className}: XCTestCase {`,
    "    override func setUpWithError() throws {",
    "        continueAfterFailure = false",
    "    }",
    "",
  ]
    .filter((l) => l !== "")
    .join("\n");
  const methods = cases.map(renderCaseMethod).join("\n\n");
  return `${header}\n${methods}\n}\n`;
}

/** The XForgeTestSupport interface (blueprint §14) — DEBUG-only, opt-in. */
export function generateTestSupportFile(): string {
  return [
    "// Generated by XForge Test. DEBUG-only; enabled via the --xforge-test",
    "// launch argument. Contains NO production behavior — only test hooks.",
    "#if DEBUG",
    "import Foundation",
    "",
    "public enum XForgeTestSupport {",
    "    public static var isEnabled: Bool {",
    '        ProcessInfo.processInfo.arguments.contains("--xforge-test")',
    "    }",
    "",
    "    public static func configure() {",
    "        guard isEnabled else { return }",
    "        configureDeterministicClock()",
    "        configureMockNetworking()",
    "        configureSeedData()",
    "        disableAnimations()",
    "    }",
    "",
    "    private static func configureDeterministicClock() {}",
    "    private static func configureMockNetworking() {}",
    "    private static func configureSeedData() {}",
    "    private static func disableAnimations() {}",
    "}",
    "#endif",
    "",
  ].join("\n");
}
