import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { basename, join, relative } from "node:path";
import { XFORGE_VERSION, type Logger } from "@xforge/shared";
import {
  appendixDir,
  detectProject,
  globRootDir,
  loadConfig,
  parsePlist,
  plistFacts,
  readTextFileSafe,
  scanFiles,
  statePath,
  type DetectionResult,
  type XForgeConfig,
} from "@xforge/core";
import {
  ensureTestDirs,
  loadTestConfig,
  parseApprovalManifest,
  parseTestPlan,
  planFilePath,
  plansDir,
  testConfigPath,
  verifyApproval,
  writeTestConfig,
  type TestConfig,
} from "@xforge/test-core";
import { emitResult, type CliContext } from "../context.js";

export interface UpgradeOptions {
  /** Report what would change without writing anything. */
  dryRun?: boolean;
}

export interface UpgradeResult {
  projectRoot: string;
  dryRun: boolean;
  /** Version that produced the current state, when it is recorded. */
  generatedBy?: string;
  currentVersion: string;
  /** Config values this run resolved and filled in. */
  filled: Array<{ key: string; value: string }>;
  /** Values left alone because the project already set them. */
  kept: Array<{ key: string; value: string }>;
  /** Values still unresolved; listed so they can be filled by hand. */
  unresolved: string[];
  createdTestConfig: boolean;
  /** Things the upgrade cannot fix, with the command that does. */
  actions: Array<{ what: string; run: string }>;
}

/**
 * `xforge upgrade` — bring a project initialized by an older XForge up to date.
 *
 * Everything XForge *generates* is safe to regenerate: `docs` rewrites the tree
 * and preserves manual blocks, and the model heals itself. What is not safe to
 * regenerate is the project's *configuration*, because it holds hand-written
 * values — `init --force` would overwrite an edited `features:` map or output
 * language, which is why it is the wrong tool for an upgrade.
 *
 * So this command only ever *adds*: it fills configuration fields still sitting
 * at their `auto` sentinel with values it can resolve from the Xcode project,
 * and reports everything else as an action for the user to take. It never
 * overwrites a value the project already set.
 */
export async function runUpgrade(
  ctx: CliContext,
  options: UpgradeOptions = {},
): Promise<UpgradeResult> {
  const { projectRoot, logger } = ctx;
  const config = await loadConfig(projectRoot); // fails clearly when not initialized

  const detection = await detect(projectRoot);
  const testConfigExisted = existsSync(testConfigPath(projectRoot));
  const testConfig = await loadTestConfig(projectRoot);

  const filled: UpgradeResult["filled"] = [];
  const kept: UpgradeResult["kept"] = [];
  const xcode = detection.xcode;

  // Fill only what the project has not decided for itself.
  const candidates: Array<[keyof TestConfig["project"], string | undefined]> = [
    ["workspace", xcode?.workspace],
    ["project", xcode?.project],
    ["scheme", xcode?.scheme],
    ["app_bundle_id", xcode?.appBundleId],
    ["ui_test_target", xcode?.uiTestTarget],
  ];
  for (const [key, resolved] of candidates) {
    const current = testConfig.project[key];
    if (current !== "auto") {
      kept.push({ key: `project.${key}`, value: String(current) });
      continue;
    }
    if (!resolved) continue;
    testConfig.project[key] = resolved;
    filled.push({ key: `project.${key}`, value: resolved });
  }

  const wroteTestConfig =
    !options.dryRun && (!testConfigExisted || filled.length > 0);
  if (wroteTestConfig) {
    await ensureTestDirs(projectRoot);
    await writeTestConfig(projectRoot, testConfig);
  }

  const generatedBy = await readGeneratorVersion(projectRoot);
  const actions: UpgradeResult["actions"] = [];

  // Version drift is a hint, not proof: a project can sit on the same version
  // string while missing artifacts a later build introduced. Check for the
  // artifacts themselves — that is the signal that cannot be wrong.
  const missingArtifacts = missingStateArtifacts(projectRoot);
  if (missingArtifacts.length > 0) {
    actions.push({
      what:
        `Generated state predates this build (missing: ${missingArtifacts.join(", ")}).` +
        " Regenerating is safe — manual blocks are preserved.",
      run: "xforge docs",
    });
  } else if (generatedBy && generatedBy !== XFORGE_VERSION) {
    actions.push({
      what: `Documentation was generated by ${generatedBy}; this is ${XFORGE_VERSION}.`,
      run: "xforge docs",
    });
  }

  // An approval is bound to a plan hash, so a model or schema change makes it
  // stale by design. Report it rather than let `test run` fail later.
  for (const planId of await stalePlans(projectRoot)) {
    actions.push({
      what: `Plan ${planId} has an approval that no longer matches its inputs.`,
      run: `xforge test plan && xforge test approve <new-plan-id>`,
    });
  }

  const missingIgnores = await missingGitignoreEntries(projectRoot);
  if (missingIgnores.length > 0) {
    actions.push({
      what: `.gitignore is missing XForge run artifacts: ${missingIgnores.join(", ")}`,
      run: `printf '\\n${missingIgnores.join("\\n")}\\n' >> .gitignore`,
    });
  }

  // A project initialized before the input/output split writes into
  // `docs/project`, which is now the tree `docs` *reads* as its source of
  // truth. Left alone, the next run would parse XForge's own generated prose
  // into requirements and report perfect coverage of them. This is the one
  // upgrade the tool cannot make for you: moving generated files is safe, but
  // choosing where a project keeps its documentation is not our decision.
  const overlap = overlappingDocTrees(config);
  if (overlap) {
    actions.push({
      what:
        `output.root (${overlap.output}) is inside sources.project_docs ` +
        `(${overlap.glob}), so \`xforge docs\` would read its own output as ` +
        "the project's requirements. Point output.root at a separate tree " +
        "— docs/xforge is the new default — and keep your own documents " +
        "where they are.",
      run: "edit .xforge/config.yaml: output.root: docs/xforge",
    });
  }

  const result: UpgradeResult = {
    projectRoot,
    dryRun: Boolean(options.dryRun),
    ...(generatedBy ? { generatedBy } : {}),
    currentVersion: XFORGE_VERSION,
    filled,
    kept,
    unresolved: xcode?.unresolved ?? [],
    createdTestConfig: !testConfigExisted && wroteTestConfig,
    actions,
  };

  emitResult(ctx, result as unknown as Record<string, unknown>, () =>
    render(logger, result, projectRoot),
  );
  return result;
}

/**
 * Detect the pre-split layout: XForge writing into the tree it now reads as the
 * project's source of truth. Returns the offending pair, or undefined when the
 * two trees are properly separate.
 */
function overlappingDocTrees(
  config: XForgeConfig,
): { output: string; glob: string } | undefined {
  const output = config.output.root.replace(/\/+$/, "");
  for (const glob of config.sources.project_docs) {
    const docsRoot = globRootDir(glob);
    if (!docsRoot) continue;
    if (output === docsRoot || output.startsWith(`${docsRoot}/`)) {
      return { output, glob };
    }
  }
  return undefined;
}

/** Re-run detection with the same inputs `init` uses. */
async function detect(projectRoot: string): Promise<DetectionResult> {
  const files = await scanFiles(projectRoot);
  const packageSwiftEntry = files.find((f) => f.path.endsWith("Package.swift"));
  const podfileEntry = files.find((f) => basename(f.path) === "Podfile");

  const pbxproj: Array<{ path: string; content: string }> = [];
  for (const file of files.filter((f) => f.path.endsWith("project.pbxproj"))) {
    const content = await readTextFileSafe(projectRoot, file.path);
    if (content !== null) pbxproj.push({ path: file.path, content });
  }
  const infoPlistEntry = files.find(
    (f) => /(^|\/)Info\.plist$/.test(f.path) && !f.sensitive,
  );
  const infoPlistBundleId = infoPlistEntry
    ? plistFacts(
        parsePlist(
          (await readTextFileSafe(projectRoot, infoPlistEntry.path)) ?? "",
        ),
      ).bundleIdentifier
    : undefined;

  return detectProject(files, {
    packageSwift: packageSwiftEntry
      ? await readTextFileSafe(projectRoot, packageSwiftEntry.path)
      : null,
    podfile: podfileEntry
      ? await readTextFileSafe(projectRoot, podfileEntry.path)
      : null,
    pbxproj,
    ...(infoPlistBundleId ? { infoPlistBundleId } : {}),
  });
}

/** Which version last generated the docs, if the state records it. */
async function readGeneratorVersion(
  projectRoot: string,
): Promise<string | undefined> {
  for (const key of ["generationState", "projectModel"] as const) {
    const path = statePath(projectRoot, key);
    if (!existsSync(path)) continue;
    try {
      const raw = JSON.parse(await readFile(path, "utf8")) as {
        generator_version?: string;
        metadata?: { generator_version?: string };
      };
      const version = raw.generator_version ?? raw.metadata?.generator_version;
      if (version) return version;
    } catch {
      continue;
    }
  }
  return undefined;
}

/**
 * State artifacts this build writes. A project missing any of them was
 * generated by an older XForge, whatever its recorded version says.
 */
function missingStateArtifacts(projectRoot: string): string[] {
  const expected: Array<[string, string]> = [
    ["model-digest.json", statePath(projectRoot, "modelDigest")],
    ["dependency-graph.json", statePath(projectRoot, "dependencyGraph")],
    ["feature-map.json", statePath(projectRoot, "featureMap")],
    ["requirement-map.json", statePath(projectRoot, "requirementMap")],
    ["generation-state.json", statePath(projectRoot, "generationState")],
    ["state/model/", appendixDir(projectRoot)],
  ];
  return expected.filter(([, path]) => !existsSync(path)).map(([name]) => name);
}

/** Approved plans whose approval no longer verifies against the plan. */
async function stalePlans(projectRoot: string): Promise<string[]> {
  const dir = plansDir(projectRoot);
  if (!existsSync(dir)) return [];
  const { readdir } = await import("node:fs/promises");
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }

  const stale: string[] = [];
  for (const planId of entries) {
    const planPath = planFilePath(projectRoot, planId, "plan");
    const approvalPath = planFilePath(projectRoot, planId, "approval");
    if (!existsSync(planPath) || !existsSync(approvalPath)) continue;
    try {
      const plan = parseTestPlan(JSON.parse(await readFile(planPath, "utf8")));
      const approval = parseApprovalManifest(
        JSON.parse(await readFile(approvalPath, "utf8")),
      );
      if (!verifyApproval(plan, approval).valid) stale.push(planId);
    } catch {
      // An unreadable plan predates the current schema; re-planning fixes it.
      stale.push(planId);
    }
  }
  return stale;
}

/** XForge run artifacts a consuming project should not commit. */
const REQUIRED_IGNORES = ["qa-runs/", ".xforge/cache/", ".xforge/logs/"];

async function missingGitignoreEntries(projectRoot: string): Promise<string[]> {
  const path = join(projectRoot, ".gitignore");
  if (!existsSync(path)) return REQUIRED_IGNORES;
  const content = await readFile(path, "utf8");
  const lines = new Set(
    content
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean),
  );
  return REQUIRED_IGNORES.filter((entry) => !lines.has(entry));
}

function render(
  logger: Logger,
  result: UpgradeResult,
  projectRoot: string,
): void {
  if (result.dryRun) {
    logger.info("Dry run — nothing was written");
  } else {
    logger.success(`XForge ${result.currentVersion}`);
  }

  if (result.generatedBy && result.generatedBy !== result.currentVersion) {
    process.stderr.write(
      `\n  State was generated by ${result.generatedBy}; this CLI is ${result.currentVersion}.\n`,
    );
  }

  if (result.createdTestConfig) {
    process.stderr.write(
      `\n  Created ${relative(projectRoot, testConfigPath(projectRoot))}\n`,
    );
  }
  if (result.filled.length > 0) {
    process.stderr.write("\n  Filled in (were `auto`):\n");
    for (const { key, value } of result.filled) {
      process.stderr.write(`    ${key} = ${value}\n`);
    }
  }
  if (result.kept.length > 0) {
    process.stderr.write("\n  Left as you set them:\n");
    for (const { key, value } of result.kept) {
      process.stderr.write(`    ${key} = ${value}\n`);
    }
  }
  if (result.unresolved.length > 0) {
    process.stderr.write(
      `\n  ! Still unresolved: ${result.unresolved.join(", ")}\n` +
        "    Fill these in by hand — find them with `xcodebuild -list`.\n",
    );
  }

  if (result.actions.length === 0) {
    process.stderr.write("\n  Everything is up to date.\n");
    return;
  }
  process.stderr.write("\n  Next:\n");
  for (const action of result.actions) {
    process.stderr.write(`    - ${action.what}\n      → ${action.run}\n`);
  }
}
