import { existsSync } from "node:fs";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { ConfigError } from "@xforge/shared";
import { formatZodIssues } from "@xforge/core";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { TEST_CONFIG_VERSION, TestConfig } from "./schema.js";
import { DesignMap } from "./design-map.js";

export * from "./schema.js";
export * from "./design-map.js";

/** Relative path of the test config within a project root. */
export const TEST_CONFIG_RELATIVE_PATH = ".xforge/test/config.yaml";

export function testConfigPath(projectRoot: string): string {
  return join(projectRoot, TEST_CONFIG_RELATIVE_PATH);
}

/** Validate an already-parsed test config, applying defaults + version check. */
export function validateTestConfig(input: unknown): TestConfig {
  if (typeof input !== "object" || input === null) {
    throw new ConfigError("Test config must be a YAML mapping");
  }
  const version = (input as Record<string, unknown>).version;
  if (version !== undefined && version !== TEST_CONFIG_VERSION) {
    throw new ConfigError(
      `Unsupported test config version ${String(version)}; expected ${TEST_CONFIG_VERSION}`,
      { details: { found: version, supported: TEST_CONFIG_VERSION } },
    );
  }
  const result = TestConfig.safeParse(input);
  if (!result.success) {
    throw new ConfigError("Test config failed validation", {
      details: { issues: formatZodIssues(result.error) },
    });
  }
  return result.data;
}

/** Build a default test config with all schema defaults applied. */
export function defaultTestConfig(): TestConfig {
  return validateTestConfig({ version: TEST_CONFIG_VERSION });
}

/**
 * Load the test config, returning defaults if none exists yet (planning can run
 * with sensible defaults before the user writes an explicit test config).
 */
export async function loadTestConfig(projectRoot: string): Promise<TestConfig> {
  const path = testConfigPath(projectRoot);
  if (!existsSync(path)) return defaultTestConfig();
  let raw: unknown;
  try {
    raw = parseYaml(await readFile(path, "utf8"));
  } catch (cause) {
    throw new ConfigError(`Test config at ${path} is not valid YAML`, {
      cause,
    });
  }
  return validateTestConfig(raw);
}

export function serializeTestConfig(config: TestConfig): string {
  const body = stringifyYaml(config, { indent: 2 });
  const header = [
    "# XForge Test configuration (see blueprint §26).",
    "# Generated by `xforge init`; safe to edit and commit.",
    "#",
    "# `project.*` values are resolved from the Xcode project. Any left as",
    "# `auto` could not be detected and must be filled in before",
    "# `xforge test run --execute` — find them with `xcodebuild -list`.",
  ].join("\n");
  return `${header}\n${body}`;
}

export async function writeTestConfig(
  projectRoot: string,
  config: TestConfig,
): Promise<string> {
  const path = testConfigPath(projectRoot);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, serializeTestConfig(config), "utf8");
  return path;
}

/** Load the design map if present (returns null when absent). */
export async function loadDesignMap(
  projectRoot: string,
  relativePath: string,
): Promise<DesignMap | null> {
  const path = join(projectRoot, relativePath);
  if (!existsSync(path)) return null;
  let raw: unknown;
  try {
    raw = parseYaml(await readFile(path, "utf8"));
  } catch (cause) {
    throw new ConfigError(`Design map at ${path} is not valid YAML`, { cause });
  }
  const result = DesignMap.safeParse(raw);
  if (!result.success) {
    throw new ConfigError("Design map failed validation", {
      details: { issues: formatZodIssues(result.error) },
    });
  }
  return result.data;
}
