import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { ConfigError } from "@xforge/shared";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { formatZodIssues } from "../project-model/index.js";
import { CONFIG_VERSION, XForgeConfig } from "./schema.js";

export * from "./schema.js";

/** Relative path of the config file within a project root. */
export const CONFIG_RELATIVE_PATH = ".xforge/config.yaml";

/** Resolve the absolute config path for a project root. */
export function configPath(projectRoot: string): string {
  return join(projectRoot, CONFIG_RELATIVE_PATH);
}

/**
 * Validate an already-parsed config object. Applies schema defaults and checks
 * version compatibility (blueprint §27.20 — patch/minor upgrades must not break
 * an existing config).
 */
export function validateConfig(input: unknown): XForgeConfig {
  if (typeof input !== "object" || input === null) {
    throw new ConfigError("Config must be a YAML mapping");
  }
  const version = (input as Record<string, unknown>).version;
  if (version !== undefined && version !== CONFIG_VERSION) {
    if (typeof version === "number" && version > CONFIG_VERSION) {
      throw new ConfigError(
        `Config version ${version} is newer than supported (${CONFIG_VERSION}). Upgrade XForge.`,
        { details: { found: version, supported: CONFIG_VERSION } },
      );
    }
    throw new ConfigError(
      `Unsupported config version ${String(version)}; expected ${CONFIG_VERSION}`,
      { details: { found: version, supported: CONFIG_VERSION } },
    );
  }
  const result = XForgeConfig.safeParse(input);
  if (!result.success) {
    throw new ConfigError("Config failed validation", {
      details: { issues: formatZodIssues(result.error) },
    });
  }
  return result.data;
}

/** Load and validate `.xforge/config.yaml` from a project root. */
export async function loadConfig(projectRoot: string): Promise<XForgeConfig> {
  const path = configPath(projectRoot);
  if (!existsSync(path)) {
    throw new ConfigError(
      `No XForge config found at ${CONFIG_RELATIVE_PATH}. Run \`xforge init\` first.`,
      { details: { path } },
    );
  }
  let text: string;
  try {
    text = await readFile(path, "utf8");
  } catch (cause) {
    throw new ConfigError(`Unable to read config at ${path}`, { cause });
  }
  let raw: unknown;
  try {
    raw = parseYaml(text);
  } catch (cause) {
    throw new ConfigError(`Config at ${path} is not valid YAML`, { cause });
  }
  return validateConfig(raw);
}

/** Serialize a config to YAML (with a header comment). */
export function serializeConfig(config: XForgeConfig): string {
  const body = stringifyYaml(config, { indent: 2 });
  return `# XForge configuration — see https://github.com/your-org/xforge\n# Generated by \`xforge init\`. Safe to edit and commit.\n${body}`;
}

/** Write a config to `.xforge/config.yaml`, creating parent dirs. */
export async function writeConfig(
  projectRoot: string,
  config: XForgeConfig,
): Promise<string> {
  const path = configPath(projectRoot);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, serializeConfig(config), "utf8");
  return path;
}

/**
 * Build a default config, applying all schema defaults. Callers may override
 * detected fields (project name, profile) before writing.
 */
export function defaultConfig(
  overrides: Partial<{ name: string; profile: "ios-swift" | "generic" }> = {},
): XForgeConfig {
  return validateConfig({
    version: CONFIG_VERSION,
    project: {
      profile: overrides.profile ?? "ios-swift",
      name: overrides.name ?? "auto",
    },
  });
}

/**
 * The directory a source glob lives under — `docs/project/**\/*.md` is rooted at
 * `docs/project`. Used to decide which directory `init` should create so the
 * user has an obvious place to drop their documents.
 *
 * Returns undefined for a glob with no fixed prefix (`**\/*.md`), because
 * creating a directory for that would mean guessing.
 */
export function globRootDir(glob: string): string | undefined {
  const segments = glob.split("/");
  const fixed: string[] = [];
  for (const segment of segments) {
    if (segment.includes("*") || segment.includes("?")) break;
    fixed.push(segment);
  }
  // The last fixed segment is a filename, not a directory, when the glob has no
  // wildcard at all (`docs/project/prd.md`).
  if (fixed.length === segments.length && fixed.length > 0) fixed.pop();
  const root = fixed.filter((s) => s !== "" && s !== ".").join("/");
  return root === "" ? undefined : root;
}
